### ISSUE TITLE
Pact core not found in .Net Core XUnit  test

### ISSUE THREAD

**Issue by andrewcarson** [pact-foundation/pact-net#144]
I'm trying to use PactNet in a .Net Core XUnit test, when running "dotnet xunit" I get:
```
PactNet.PactFailureException : Please install the relevant platform and architecture specific PactNet dependency from Nuget. Based on your current setup you should install 'PactNet.Linux.x64'.
```

I do have the PactNet.Linux.x64 package added.

I believe this is because [Contants.cs](https://github.com/pact-foundation/pact-net/blob/69003b601d3a35c56f0067a7a7dff75643232a8b/PactNet/Constants.cs#L18) uses AppContext.BaseDirectory, which is then used in [PactCoreHost.cs](https://github.com/pact-foundation/pact-net/blob/69003b601d3a35c56f0067a7a7dff75643232a8b/PactNet/Core/PactCoreHost.cs#L27) as the expected root of the pack core path.

However, when running under XUnit in .Net core, the AppContext.BaseDirectory folder is not the same as the build directory:
```
AppContext.BaseDirectory: /home/andyc/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/
Environment.CurrentDirectory: /home/andyc/tmp/t/test/bin/Debug/netcoreapp2.0
pact-linux-x86_64 exists: True
```

You can reproduce this using the attached project: [test.tar.gz](https://github.com/pact-foundation/pact-net/files/1845582/test.tar.gz)
```
% tar xzf test.tar.gz
% cd test
% dotnet build
% dotnet xunit
Detecting target frameworks in test.csproj...
Building for framework netcoreapp2.0...
  test -> /home/andyc/tmp/test/bin/Debug/netcoreapp2.0/test.dll
Running .NET Core 2.0.5 tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.0.0)
  Discovering: test
  Discovered:  test
  Starting:    test
AppContext.BaseDirectory: /home/andyc/.nuget/packages/dotnet-xunit/2.3.1/tools/netcoreapp2.0/
Environment.CurrentDirectory: /home/andyc/tmp/test/bin/Debug/netcoreapp2.0
pact-linux-x86_64 exists: True
    test.UnitTest1.Test1 [FAIL]
      PactNet.PactFailureException : Please install the relevant platform and architecture specific PactNet dependency from Nuget. Based on your current setup you should install 'PactNet.Linux.x64'.
      Stack Trace:
        C:\projects\pact-net\PactNet\Core\PactCoreHost.cs(59,0): at PactNet.Core.PactCoreHost`1..ctor(T config)
        C:\projects\pact-net\PactNet\Mocks\MockHttpService\Host\RubyHttpHost.cs(23,0): at PactNet.Mocks.MockHttpService.Host.RubyHttpHost..ctor(Uri baseUri, String consumerName, String providerName, PactConfig config, IPAddress host)
        C:\projects\pact-net\PactNet\Mocks\MockHttpService\MockProviderService.cs(42,0): at PactNet.Mocks.MockHttpService.MockProviderService.<>c__DisplayClass12_0.<.ctor>b__0(Uri baseUri)
        C:\projects\pact-net\PactNet\Mocks\MockHttpService\MockProviderService.cs(132,0): at PactNet.Mocks.MockHttpService.MockProviderService.Start()
        C:\projects\pact-net\PactNet\PactBuilder.cs(82,0): at PactNet.PactBuilder.MockService(Int32 port, JsonSerializerSettings jsonSerializerSettings, Boolean enableSsl, IPAddress host)
        /home/andyc/tmp/test/UnitTest1.cs(24,0): at test.UnitTest1.Test1()
  Finished:    test
=== TEST EXECUTION SUMMARY ===
   test  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.231s
```

There was a similar issue for [XUnit and ASP.Net MVC](https://github.com/xunit/xunit/issues/1519l)

I can think of a couple of fixes:
1. Make the base path configurable via PactConfig. This would be pretty clunky.
2. Try probing both AppContext.BaseDirectory and Environment.CurrentDirectory.
3. Something else... maybe try to find the test assembly location and probe there?

I'm happy to write something and make a pull request if you express a preference...

**Comment by neilcampbell** [comment]
Hmm. Yeah that is a tricky one, it definitely did work, I just can't remember if it was in a netcore1.0 scenario.

A PR would be amazing!

I think ideally we want find the test assembly location and probe there. Potentially we could fallback to AppContext.BaseDirectory.

**Comment by DennisJantos** [comment]
I had the same issue.

I created a fork and changed the PactCoreHost.cs. The following approach worked for me: https://github.com/DennisJantos/pact-net/commit/e0f6d6bf5f2b00474d29aa2b5dd16aabc7a351f7

Is there any update on this issue?

**Comment by andrewcarson** [comment]
I have to admit, I started looking at it, but stalled, struggling to get the unit tests working under Linux/.Net Core.
