### ISSUE TITLE
Encoding problem when reading .pact file from local filesystem

### ISSUE THREAD

**Issue by JoshKeegan** [pact-foundation/pact-net#207]
I'm having this issue using the latest version of PactNet.Windows (2.4.7).

I have a .pact file generated that contains some strings with the British pound sign in (£).
The consumer tests work fine, generating the pact.json file. When I run the provider tests against this pact file on my local filesystem, I get an error:
```
* Expected "\u252C\u00FA19.99" but got "\u00A319.99" at $.data.items[0].price.menuPrice.formatted
* Expected "\u252C\u00FA19.99" but got "\u00A319.99" at $.data.items[0].price.adjustedPrice.formatted
...
```
The result appears to be correct, but the expected value is not the "£" sign. I have checked the JSON file manually and the encoding is correct (UTF-8) and the value's expected have the pound sign.

When I serve the same file from a local instance of nginx, and point the pact provider tests at the same .pact file over http, everything works as expected and the test passes, so I believe there is an encoding related bug when reading from the local filesystem.

**Comment by bethesque** [comment]
@JoshKeegan can you see if you can recreate it using this please? https://github.com/pact-foundation/pact-ruby-standalone-e2e-example

**Comment by JoshKeegan** [comment]
Done :)
I ran this in debian (as the setup instructions were for linux) and my original issue was on windows, so we can also rule out anything platform specific.

Link to repo: https://github.com/JoshKeegan/pact-ruby-standalone-e2e-example

Console output:
```
INFO  WEBrick 1.3.1
INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
WARN  TCPServer Error: Cannot assign requested address - bind(2) for "::1" port 1234
INFO  WEBrick::HTTPServer#start: pid=3167 port=1234
Cleared interactions
Registered interactions
{"formattedPrice":"£5.00"}Interactions matched
{
  "consumer": {
    "name": "Foo"
  },
  "provider": {
    "name": "Bar"
  },
  "interactions": [
    {
      "description": "foo",
      "request": {
        "method": "GET",
        "path": "/foo"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "formattedPrice": "£5.00"
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
INFO  going to shutdown ...
INFO  WEBrick::HTTPServer#start done.
/code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/builder.rb:36:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/builder.rb:36:in `parse_file'
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
        from /code/pact/lib/vendor/ruby/2.2.0/gems/rack-2.0.7/lib/rack/server.rb:148:in `start'
        from -e:1:in `<main>'
WARN: The --pact-urls option is deprecated. Please pass in a space separated list of URLs as the first arguments to the pact-provider-verifier command.
INFO: Reading pact at pacts/foo-bar.json

Verifying a pact between Foo and Bar
  Foo
    with GET /foo
      returns a response which
        has status code 200 (FAILED - 1)
        has a matching body (FAILED - 2)
        includes headers
          "Content-Type" which equals "application/json" (FAILED - 3)

Failures:

  1) Verifying a pact between Foo and Bar Foo with GET /foo returns a response which has status code 200
     Failure/Error: replay_interaction interaction, options[:request_customizer]

     Errno::EADDRNOTAVAIL:
       Cannot assign requested address - connect(2) for "localhost" port 9292

  2) Verifying a pact between Foo and Bar Foo with GET /foo returns a response which has a matching body
     Failure/Error: replay_interaction interaction, options[:request_customizer]

     Errno::EADDRNOTAVAIL:
       Cannot assign requested address - connect(2) for "localhost" port 9292

  3) Verifying a pact between Foo and Bar Foo with GET /foo returns a response which includes headers "Content-Type" which equals "application/json"
     Failure/Error: replay_interaction interaction, options[:request_customizer]

     Errno::EADDRNOTAVAIL:
       Cannot assign requested address - connect(2) for "localhost" port 9292

1 interaction, 1 failure

Failed interactions:

* Foo

script/provider-verify-pact.sh: line 11: kill: (3205) - No such process
```
