### ISSUE TITLE
Getting an error when building regex with '\b' boundary 

### ISSUE THREAD

**Issue by Morshed11218** [pact-foundation/pact-net#218]
I'm getting the following exception when trying to build a regex with '\b' boundary 

regex expression: **(?=.*Id)(?=.*in)(?=.*\bee3e011c-b38e-4a5b-8729-235a62f10170\b).*$**

PactNet.PactFailureException
  HResult=0x80131500
  Message={"message":"Error ocurred in mock service: RuntimeError - Value to generate \"(?=.*Id)(?=.*in)(?=.*\\bee3e011c-b38e-4a5b-8729-235a62f10170\\b).*$\" does not match regular expression /(?=.*Id)(?=.*in)(?=.*\\bee3e011c-b38e-4a5b-8729-235a62f10170\\b).*$/","backtrace":["C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-support-1.7.2/lib/pact/term.rb:30:in `initialize'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-support-1.7.2/lib/pact/term.rb:12:in `new'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-support-1.7.2/lib/pact/term.rb:12:in `json_create'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/json-2.1.0/lib/json/common.rb:335:in `load'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/mock_service/request_handlers/interaction_post.rb:26:in `respond'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/mock_service/request_handlers/base_request_handler.rb:17:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.5/lib/rack/cascade.rb:33:in `block in call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.5/lib/rack/cascade.rb:24:in `each'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.5/lib/rack/cascade.rb:24:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/consumer/mock_service/cors_origin_header_middleware.rb:11:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/consumer/mock_service/error_handler.rb:13:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/mock_service/app.rb:33:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/pact-mock_service-2.10.1/lib/pact/consumer/mock_service/set_location.rb:14:in `call'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'","C:/Users/morsh/source/repos/dummy/tests/dummy.IntegrationTest/bin/Debug/netcoreapp2.2/pact-win32/lib/vendor/ruby/2.2.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'"]}
  Source=PactNet
  StackTrace:
   at PactNet.Mocks.MockHttpService.AdminHttpClient.SendAdminHttpRequest[T](HttpVerb method, String path, T requestContent, IDictionary`2 headers)
   at PactNet.Mocks.MockHttpService.MockProviderService.RegisterInteraction()
   at dummy.IntegrationTest.Pact.PactExtension.MockContract(IMockProviderService pact, String description, String state, ProviderServiceRequest request, ProviderServiceResponse response) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Pact\PactExtension.cs:line 16
   at dummy.IntegrationTest.Pact.PactExtension.Mock(IMockProviderService pact, ProviderServiceRequest request, ProviderServiceResponse response, String description, String state) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Pact\PactExtension.cs:line 11
   at dummy.IntegrationTest.Pact.ServiceDecorators.CrossAssetServiceMockDecorator.MockUserBulkResolver(SearchCriteriaField searchCriteriaField, String[] ids, Object[] responseObj, String description, String state) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Pact\ServiceDecorators\CrossAssetServiceMockDecorator.cs:line 971
   at dummy.IntegrationTest.Pact.ServiceDecorators.CrossAssetServiceMockDecorator.MockCrossAssetUserInternalExternal(String userId, String userIdResolved) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Pact\ServiceDecorators\CrossAssetServiceMockDecorator.cs:line 130
   at dummy.IntegrationTest.Helpers.DefaultMockServices.MockDefaultCrossAssetServices() in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Helpers\DefaultMockServices.cs:line 52
   at dummy.IntegrationTest.Tests.BaseIndicationApiTests`1..ctor(IndicationService`1 service) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Tests\BaseIndicationApiTests.cs:line 54
   at dummy.IntegrationTest.Tests.IssueBookIndicationApiTests..ctor(IndicationService`1 service) in C:\Users\morsh\Source\Repos\dummy\tests\dummy.IntegrationTest\Tests\IssueBookIndicationApiTests.cs:line 30

**Comment by neilcampbell** [comment]
It needs to be a valid ruby regex, so it might be something to do with that. You might need to even escape the \b. I'd try breaking the expression in to smaller chunks and debugging that way.
