### ISSUE TITLE
`Ignoring json-2.2.0 because its extensions are not built.` error

### ISSUE THREAD

**Issue by donaldgray** [pact-foundation/pact-net#222]
I am looking to make changes to a project where PACT tests were previously working, however when I run I get a `PactFailureException` with the error `Ignoring json-2.2.0 because its extensions are not built.  Try: gem pristine json --version 2.2.0`.

I'm running on Windows and have PactNet and PactNet.Windows version 2.4.8 installed (was 2.4.6). Running on dotnetcore 2.2. I don't have Ruby installed on the system at all, the only time it's used is for PACT tests.

```
PactNet.PactFailureException : Pact verification failed. See output for details. 
If the output is empty please provide a custom config.Outputters (IOutput) for your test framework, as we couldn't write to the console.
   at PactNet.Core.PactCoreHost`1.Start() in C:\projects\pact-net\PactNet\Core\PactCoreHost.cs:line 139
   at MyProject.PactTests.Provider.MyProjectTests.EnsurePost_WithRegistrationData_HonoursPactWithConsumer() in C:\Users\_\repo\src\project\MyProject.PactTests\Provider\Verifier.cs:line 69

Ignoring json-2.2.0 because its extensions are not built.  Try: gem pristine json --version 2.2.0
C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/vendor/molinillo/lib/molinillo/modules/specification_provider (LoadError)
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:115:in `<class:Resolution>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:4:in `<class:Resolver>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:2:in `<module:Molinillo>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:1:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:10:in `<class:Resolver>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:9:in `<module:Molinillo>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:3:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendor/molinillo/lib/molinillo.rb:3:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/vendored_molinillo.rb:2:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/resolver.rb:12:in `<class:Resolver>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/resolver.rb:10:in `<module:Bundler>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/resolver.rb:9:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:192:in `resolve'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from C:/Users/_/repo/src/project/MyProject.PactTests/bin/Debug/netcoreapp2.2/pact-win32/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

**Comment by neilcampbell** [comment]
@donaldgray Did the issue only start happening when you upgraded?
You shouldn't need Ruby install, so that should be fine. 
Are you able to create an sample reproduction repo, so I can try on my machine?

**Comment by donaldgray** [comment]
No, I upgraded due to the issue thinking that maybe something got outdated or had a collision with another package.
Will try and get an isolated reproduction today.

**Comment by donaldgray** [comment]
@neilcampbell - I'm going to close this as I think it's related to path length. As you can see from the message the path is pretty long, I removed it from the logging message but the name of the project is "image-registration-lookup" which adds quite a lot of characters.

I cloned the repo to `c:\a\` and it's working okay now.

**Comment by neilcampbell** [comment]
Ah yep, that one is a pain! Thanks for the update.
