### ISSUE TITLE
PactNet.Linux.x64 2.5.0 Fails with Ruby Error

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-net#231]
When I run PactNet.Linux.x64 v2.5.0 in a Docker container, I get the following Ruby-related error on every interaction:

```
Error reading file from 'http://pactbroker.mydomain.local/pacts/provider/Provider/consumer/Consumer/latest/master'
No such file or directory @ rb_sysopen - 'http://pactbroker.mydomain.local/pacts/provider/Provider/consumer/Consumer/latest/master' /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:51:in `read'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:51:in `get_local'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:22:in `read'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_source.rb:14:in `pact_json'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:116:in `collect'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:116:in `pact_jsons'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:79:in `configure_rspec'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:67:in `run_with_pact_uri_object'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:50:in `run_specs'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:161:in `verify_pact'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:41:in `block in call'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:40:in `collect'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:40:in `call'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:32:in `call'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/cli/verify.rb:53:in `verify'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/app/pact-provider-verifier.rb:33:in `<main>'
/app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:51:in `read': No such file or directory @ rb_sysopen - 'http://pactbroker.mydomain.local/pacts/provider/Provider/consumer/Consumer/latest/master' (Errno::ENOENT)
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:51:in `get_local'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:41:in `render_pact'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-support-1.12.0/lib/pact/consumer_contract/pact_file.rb:22:in `read'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_source.rb:14:in `pact_json'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:116:in `collect'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:116:in `pact_jsons'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:79:in `configure_rspec'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:67:in `run_with_pact_uri_object'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:50:in `run_specs'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.43.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:161:in `verify_pact'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:41:in `block in call'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:40:in `collect'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:40:in `call'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/app.rb:32:in `call'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/cli/verify.rb:53:in `verify'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.26.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
        from /app/tests/MyProject.Pacts/bin/Release/netcoreapp2.1/pact-linux-x86_64/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

The important bit is `No such file or directory @ rb_sysopen`

Downgrading to 2.4.8 works fine. I'm wondering if the bundled standalone pact has been upgraded and caused this issue.

**Comment by vikpck** [comment]
Wasted a day on this myself. Going back to 2.4.8. Thank you for raising the issue.

**Comment by namhuynhkien** [comment]
Happened to me in MAC as well. 2.4.8 works fine

**Comment by bethesque** [comment]
Yes, the ruby standalone has been updated. But the issue hasn't been reported on any other wrapped language. For some reason it thinks it's a local file, not a remote one. That logic hasn't changed for ages. I wonder if it's an escaping or encoding issue. The logic it does to work out if it's a remote or local file is:

```ruby
def local? uri
      !uri.start_with?("http://", "https://")
    end
```

For some reason, that's failing now.

**Comment by bethesque** [comment]
@adamrodger if you can provide me with a docker container to recreate the issue, I will investigate.

**Comment by namhuynhkien** [comment]
@bethesque can you on Mac? it's failing in my project even with the remote one

**Comment by adamrodger** [comment]
I'll try to come up with a sample repo to reproduce. Might not be today
though

**Comment by neilcampbell** [comment]
I wonder if it's due to changing "" to '' when wrapping valves for args.

**Comment by bethesque** [comment]
I don't know anything about .net @namhuynhkien. That's why I'll need someone to provide me with a runnable container to debug. I can help with the ruby side.

I have a mac, fyi.

**Comment by neilcampbell** [comment]
Fixed in 2.5.1

**Comment by bethesque** [comment]
What was the fix @neilcampbell?

**Comment by neilcampbell** [comment]
@bethesque It was https://github.com/pact-foundation/pact-net/commit/9d78708bb5f3f3df4f8645e737259445eb8f4cb4. Basically changing back to using `"` rather than `'`.

**Comment by bethesque** [comment]
Ah, that old chestnut.
