### ISSUE TITLE
.NET 3.1 Support On Windows

### ISSUE THREAD

**Issue by AshleyPoole** [pact-foundation/pact-net#243]
When using Pact on Windows for .NET 3.1, it fails to work (even with long path support enabled). As mentioned in #242 already, I have tried upgrading the sample application and tests to .NET 3.1 and they fail.

Here's one of the stack traces after upgrading the tests to .NET 3.1:
```
X Consumer.Tests.EventsApiConsumerTests.CreateEvent_WhenCalledWithEvent_Succeeds [1ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (One or more errors occurred. (No connection could be made because the target machine actively refused it.)) (The following constructor parameters did not have matching fixture data: ConsumerEventApiPact data)
---- System.AggregateException : One or more errors occurred. (No connection could be made because the target machine actively refused it.)
-------- System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it.
------------ System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
---- The following constructor parameters did not have matching fixture data: ConsumerEventApiPact data
  Stack Trace:

----- Inner Stack Trace #1 (System.AggregateException) -----
   at PactNet.Mocks.MockHttpService.Host.RubyHttpHost.Start() in C:\Users\AshleyPoole\Downloads\pact-net-master-3\pact-net-master\PactNet\Mocks\MockHttpService\Host\RubyHttpHost.cs:line 66
   at PactNet.Mocks.MockHttpService.MockProviderService.Start() in C:\Users\AshleyPoole\Downloads\pact-net-master-3\pact-net-master\PactNet\Mocks\MockHttpService\MockProviderService.cs:line 137
   at PactNet.PactBuilder.MockService(Int32 port, JsonSerializerSettings jsonSerializerSettings, Boolean enableSsl, IPAddress host, String sslCert, String sslKey) in C:\Users\AshleyPoole\Downloads\pact-net-master-3\pact-net-master\PactNet\PactBuilder.cs:line 101
   at PactNet.PactBuilder.MockService(Int32 port, Boolean enableSsl, IPAddress host, String sslCert, String sslKey) in C:\Users\AshleyPoole\Downloads\pact-net-master-3\pact-net-master\PactNet\PactBuilder.cs:line 70
   at Consumer.Tests.ConsumerEventApiPact..ctor() in C:\Users\AshleyPoole\Downloads\pact-net-master-3\pact-net-master\Samples\EventApi\Consumer.Tests\ConsumerEventApiPact.cs:line 28
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by vpsouza** [comment]
Same for me. I'm leaving it after spent 8h without success. A several ruby process lost... I though Pact-JVM is absurdly more robust (and stable) than Pact-Net.

**Comment by raschmitt** [comment]
Working fine for me on 3.1, just had to move my code to a shallow directory.

**Comment by AshleyPoole** [comment]
I think the issue isn't long path support on Windows but rather the Ruby runtime used by Pact, hence why shallow directory paths work. Sadly this isn't possible for all projects.

**Comment by rodrigoramos** [comment]
That's a very annoying issue. 
The best workaround that I have found was to map the project folder as a drive.

```
subst x: \path\to\long\folder
```

Source: https://stackoverflow.com/a/1880494
