### ISSUE TITLE
Proxy settings not used in PactPublisher (for proxy with settings)

### ISSUE THREAD

**Issue by marcpaulv** [pact-foundation/pact-net#287]
The `PactPublisher` cannot be used to communicate with the PACT broker from an environment behind a proxy.

```csharp
TearDown : System.Net.Http.HttpRequestException : An error occurred while sending the request.
  ----> System.Net.WebException : The remote server returned an error: (407) Proxy Authentication Required.
--TearDown
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PactNet.PactPublisher.<PublishToBrokerAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PactNet.Core.Async.RunSync(Func`1 task)
   at testclass.CreatePact() in testclass.cs:line 51
--WebException
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
```

Although the `PactUriOptions.HttpProxy` can be set and passed to the constructor, they are not passed on to the underlying `_httpClient/handler` used  to send the requests.

**Comment by bethesque** [comment]
Try setting the `http_proxy` or `https_proxy` environment variables.

**Comment by marcpaulv** [comment]
Those environment variables are not used by the `HttpClient` class.

**Comment by marcpaulv** [comment]
`http_proxy` is used in the `PactVerifier` which relies on the ruby implementation, but it is not working for a proxy that needs credentials. I opened another issue to address it https://github.com/pact-foundation/pact-net/issues/288

**Comment by adamrodger** [comment]
`PactPublisher` is deprecated from 4.x and there are currently no plans to make changes to it for 3.x and below, so closing this issue. The recommended alternative is to use the CLI to publish your pacts.

**Comment by kishorenaga** [comment]
@adamrodger when you say CLI , what should i use to to publish the contracts to pactBoker

**Comment by mefellows** [comment]
https://docs.pact.io/implementation_guides/cli#pact-broker-cli
