### ISSUE TITLE
Provider state regression in 4.4.0

### ISSUE THREAD

**Issue by dheardal** [pact-foundation/pact-net#452]
I currently have a provider test suite setup using Pact.Net 4.3.0, using the following code:

```
      new PactVerifier(config)
            .ServiceProvider("Test", _fixture.ServerUri)
            .WithPactBrokerSource(new Uri(pactBrokerUri), opts =>
            {
                opts
                    .TokenAuthentication(apiToken)
                    .ConsumerVersionSelectors(new ConsumerVersionSelector { MainBranch = true, Latest = true })
                    .PublishResults(providerVersion, results =>
                    {
                        results
                            .ProviderBranch(branchName);
                    });
            })
            .WithProviderStateUrl(new Uri(_fixture.ServerUri, "/provider-states"))
            .Verify();
```

This all works fine in 4.3.0, but as soon as i upgrade to 4.4.0 without changing any configuration I suddenly start getting these errors:

```
Request Failed - One or more of the setup state change handlers has failed
...
MismatchResult::Error("Invalid status code: 405", Some("793d03f1cf58ea18516c4e41492e368e905a5cd3"))
```

It seems as though the provider states HTTP method has changed or it is no longer being called as a post

**Comment by adamrodger** [comment]
That could be related to the change to support different provider state options in 4.4.0.

You could maybe try changing the mode to get it working whilst I investigate - it would certainly help with tracking down the issue.

**Comment by dheardal** [comment]
Do you mean this? 

```
    .WithProviderStateUrl(new Uri(_fixture.ServerUri, "/provider-states"),
        o => o.WithStyle(ProviderStateStyle.Body))
```

That's 4.5.0 not 4.4.0, but still gives the same error

**Comment by adamrodger** [comment]
Ah I thought there was a GET vs. POST option, which would make sense because you're seeing a HTTP 405 Method Not Allowed

**Comment by dheardal** [comment]
```
[xUnit.net 00:00:11.90]     RuntimeService.Test.Contract.IntegrationApiContractTests.EnsureAireFrameHonoursConsumerPacts [FAIL]
  Failed RuntimeService.Test.Contract.IntegrationApiContractTests.EnsureAireFrameHonoursConsumerPacts [5 s]
  Error Message:
   PactNet.Exceptions.PactFailureException : Pact verification failed
  Stack Trace:
     at PactNet.Verifier.InteropVerifierProvider.Execute()
   at PactNet.Verifier.PactVerifierSource.Verify()
   at RuntimeService.Test.Contract.IntegrationApiContractTests.EnsureAireFrameHonoursConsumerPacts() in /home/vsts/work/1/s/Core/RuntimeService.Test/Contract/ApiContractTests.cs:line 50
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Standard Output Messages:
 Starting verification...
 Pact verification failed
 
 Verifier Output
 ---------------
 The pact at https://airelogictest.pactflow.io/pacts/provider/AireFrame/consumer/AireFlow/pact-version/64e2e52a239a6ee48c36190be9d03b62478b7051 is being verified because the pact content belongs to the consumer version matching the following criterion:
     * latest version from the main branch 'main' (20230419.2)
 
 Verifying a pact between AireFlow and AireFrame
 
   A create form instance request with a form key which does not exist.
       Request Failed - One or more of the setup state change handlers has failed
 
   A create form instance request with a form version which does not exist.
       Request Failed - One or more of the setup state change handlers has failed
 
   A create form instance request with a subject id which does not exist.
       Request Failed - One or more of the setup state change handlers has failed
 
   A create form instance request with a user which does not exist.
       Request Failed - One or more of the setup state change handlers has failed
 
   A create form instance request without a valid auth header.
       Request Failed - One or more of the setup state change handlers has failed
 
   A valid create form instance request.
       Request Failed - One or more of the setup state change handlers has failed
 
 
 Failures:
 
 1) Verifying a pact between AireFlow and AireFrame - A create form instance request with a form key which does not exist. - One or more of the setup state change handlers has failed
 
 2) Verifying a pact between AireFlow and AireFrame - A create form instance request with a form version which does not exist. - One or more of the setup state change handlers has failed
 
 3) Verifying a pact between AireFlow and AireFrame - A create form instance request with a subject id which does not exist. - One or more of the setup state change handlers has failed
 
 4) Verifying a pact between AireFlow and AireFrame - A create form instance request with a user which does not exist. - One or more of the setup state change handlers has failed
 
 5) Verifying a pact between AireFlow and AireFrame - A create form instance request without a valid auth header. - One or more of the setup state change handlers has failed
 
 6) Verifying a pact between AireFlow and AireFrame - A valid create form instance request. - One or more of the setup state change handlers has failed
 
 
 There were 6 pact failures
 
 Verifier Logs
 -------------
 2023-04-21T08:34:58.659937Z  INFO ThreadId(03) pact_verifier::pact_broker: Fetching path '/' from pact broker
 2023-04-21T08:35:00.351126Z  INFO ThreadId(03) pact_verifier::pact_broker: Fetching path '/pacts/provider/AireFrame/for-verification' from pact broker
 2023-04-21T08:35:01.053042Z  INFO ThreadId(03) pact_verifier::pact_broker: Fetching path '/pacts/provider/AireFrame/consumer/AireFlow/pact-version/64e2e52a239a6ee48c36190be9d03b62478b7051/metadata/c1tdW2xdPXRydWUmc1tdW2N2XT0xODYx' from pact broker
 2023-04-21T08:35:01.391941Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A create form instance request with a form key which does not exist.'
 2023-04-21T08:35:01.576841Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("793d03f1cf58ea18516c4e41492e368e905a5cd3"))
 2023-04-21T08:35:01.577724Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A create form instance request with a form version which does not exist.'
 2023-04-21T08:35:01.606376Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("ce26c4a2bd780b7caaf03bda4fe82fc81ec5aa63"))
 2023-04-21T08:35:01.607219Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A create form instance request with a subject id which does not exist.'
 2023-04-21T08:35:01.614547Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("005606bc9cbd0f62909093d76a5b8c51c19d725d"))
 2023-04-21T08:35:01.615275Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A create form instance request with a user which does not exist.'
 2023-04-21T08:35:01.619963Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("7afac9c7617bd5677f1cad87129c14197be4ca7f"))
 2023-04-21T08:35:01.620629Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A create form instance request without a valid auth header.'
 2023-04-21T08:35:01.622363Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("c0a43c0162498c82a4c6c73a1536cfb95df7024e"))
 2023-04-21T08:35:01.623090Z  INFO ThreadId(03) pact_verifier: Running setup provider state change handler with empty state for 'A valid create form instance request.'
 2023-04-21T08:35:01.626157Z ERROR ThreadId(03) pact_verifier: Provider setup state change for has failed - MismatchResult::Error("Invalid status code: 405", Some("a6551afd5f1f473875ac5efdcecc3b03ee7fd5c0"))
 2023-04-21T08:35:01.626415Z  INFO ThreadId(03) pact_verifier: Publishing verification results back to the Pact Broker
```

**Comment by adamrodger** [comment]
Annoyingly that doesn't tell us what HTTP call it's making. Could you change the log level to Debug and re-run? Hopefully that'll tell us

**Comment by dheardal** [comment]
Apologies it's taken me so long to get around to this.

`2023-04-29T09:43:08.568282Z DEBUG ThreadId(01) verify_interaction{interaction="A create form instance request with a form key which does not exist."}: pact_verifier::provider_client: State change request: Response { url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9228), path: "/provider-states", query: None, fragment: None }, status: 405, headers: {"content-length": "0", "date": "Sat, 29 Apr 2023 09:43:08 GMT", "server": "Kestrel", "allow": "GET, HEAD", "cache-control": "no-store, no-cache, private", "content-language": "en-GB", "expires": "Mon, 01 Jan 0001 00:00:00 GMT", "x-content-type-options": "nosniff", "x-xss-protection": "1; mode=block", "x-frame-options": "SameOrigin", "referrer-policy": "no-referrer"} }`

This would seem to suggest that the `/provider-states` endpoint is only accepting a GET request?

**Comment by adamrodger** [comment]
Is your service definitely running on port 9228 and nothing else is running on that port?

How are you implementing the provider state endpoint?

**Comment by dheardal** [comment]
Yep definitely running on that port (those are the headers I'd expect from my service)

With this line (full config is in the first message)
` .WithProviderStateUrl(new Uri(_fixture.ServerUri, "/provider-states"))`

**Comment by adamrodger** [comment]
Sorry yeah, I was asking how you've implemented that endpoint in your service to handle the provider state requests.

**Comment by dheardal** [comment]
Ok so think that's where I've gone wrong - we haven't setup a provider state endpoint as we're not currently using provider states.

Prior to 4.4.0, it didn't seem to matter (perhaps it was using a GET request?), so removing the `WithProviderStates` allows it to work with 4.4.0 onwards
